site_name: Marlen
repo_url: httos://github.com/cbti-rj-org/marlen/
repo_name: cbti-rj-org/marlen/
edit_uri: tree/main/docs

theme:
  name: material
  language: pt-BR
  logo: assets/logo.png
  favicon: assets/logo.png

markdown_extensions: 
  - attr_list

extra_css:
  - stylesheets/extra.css

plugins:
- mkdocstrings:
    handlers:
      python:
        paths: [marlen]