# Generated by Django 4.1.7 on 2023-11-10 12:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Atividades',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=250, verbose_name='nome')),
                ('descricao', models.CharField(blank=True, max_length=250, null=True, verbose_name='descricao')),
                ('endereco', models.CharField(blank=True, max_length=250, null=True, verbose_name='endereco')),
                ('link', models.CharField(blank=True, max_length=250, null=True, verbose_name='link')),
                ('pauta', models.CharField(blank=True, max_length=250, null=True, verbose_name='pauta')),
                ('inicio', models.DateTimeField(verbose_name='Inicio')),
                ('fim', models.DateTimeField(verbose_name='fim')),
                ('tipo', models.IntegerField(choices=[(0, 'presencial'), (1, 'online'), (2, 'mista')], default=0, verbose_name='tipo')),
            ],
            options={
                'verbose_name': 'Atividade',
                'verbose_name_plural': 'Atividade',
            },
        ),
        migrations.CreateModel(
            name='Funcoes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=250, verbose_name='nome')),
                ('cadastra', models.BooleanField(default=True, verbose_name='cadastra')),
                ('financeiro', models.BooleanField(default=True, verbose_name='financeiro')),
                ('assistencia', models.BooleanField(default=False, verbose_name='assistencia')),
            ],
            options={
                'verbose_name': 'funcão',
                'verbose_name_plural': 'funcões',
            },
        ),
        migrations.CreateModel(
            name='Instancias',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.IntegerField(choices=[(0, 'nacional'), (1, 'fração'), (2, 'estadual'), (3, 'base')], default=3, verbose_name='tipo')),
                ('nome', models.CharField(max_length=250, verbose_name='nome')),
                ('categoria', models.CharField(blank=True, max_length=250, verbose_name='categoria')),
                ('slug', models.SlugField(unique=True, verbose_name='slug')),
            ],
            options={
                'verbose_name': 'instancia',
                'verbose_name_plural': 'instancias',
            },
        ),
        migrations.CreateModel(
            name='Militantes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('apelido', models.CharField(max_length=250, verbose_name='apelido')),
                ('codigo_unico', models.CharField(max_length=250, unique=True, verbose_name='codigo unico')),
                ('primeiro_acesso', models.BooleanField(default=True, verbose_name='primeiro acesso')),
                ('ativo', models.BooleanField(default=True, verbose_name='ativo')),
                ('instancias', models.ManyToManyField(related_name='militantes', to='core.instancias', verbose_name='instancias')),
                ('usuario', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='militante', to=settings.AUTH_USER_MODEL, verbose_name='usuario')),
            ],
            options={
                'verbose_name': 'militante',
                'verbose_name_plural': 'militantes',
            },
        ),
        migrations.CreateModel(
            name='Organizacoes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=20, unique=True, verbose_name='codigo')),
                ('constribuicao', models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True, verbose_name='constribuição')),
                ('nome', models.CharField(max_length=250, verbose_name='nome')),
                ('sigla', models.CharField(max_length=10, verbose_name='sigla')),
            ],
            options={
                'verbose_name': 'organização',
                'verbose_name_plural': 'organizações',
            },
        ),
        migrations.CreateModel(
            name='Secretariados',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('funcao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='militantes', to='core.funcoes', verbose_name='funcao')),
                ('instancia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='secretariado', to='core.instancias', verbose_name='instancia')),
                ('militante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='secretariados', to='core.militantes', verbose_name='militante')),
            ],
            options={
                'verbose_name': 'secretariado',
                'verbose_name_plural': 'secretariados',
            },
        ),
        migrations.CreateModel(
            name='InstanciasDados',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('banco_nome', models.CharField(blank=True, max_length=250, null=True, verbose_name='banco nome')),
                ('banco_agencia', models.CharField(blank=True, max_length=250, null=True, verbose_name='banco agencia')),
                ('banco_agencia_digito', models.CharField(blank=True, max_length=250, null=True, verbose_name='banco agencia digito')),
                ('banco_conta', models.CharField(blank=True, max_length=250, null=True, verbose_name='banco conta')),
                ('banco_conta_digito', models.CharField(blank=True, max_length=250, null=True, verbose_name='banco conta digito')),
                ('banco_codigo_pix', models.CharField(blank=True, max_length=250, null=True, verbose_name='banco codigo pix')),
                ('banco_nome_dono_conta', models.CharField(blank=True, max_length=250, null=True, verbose_name='banco nome dono conta')),
                ('banco_cpf_dono_conta', models.CharField(blank=True, max_length=250, null=True, verbose_name='banco cpf dono conta')),
                ('instancia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dados', to='core.instancias', verbose_name='instancia')),
            ],
            options={
                'verbose_name': 'instancia dados',
                'verbose_name_plural': 'instancias dados',
            },
        ),
        migrations.AddField(
            model_name='instancias',
            name='organizacao',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='instancias', to='core.organizacoes', verbose_name='organizacao'),
        ),
        migrations.AddField(
            model_name='instancias',
            name='superior',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='inferiores', to='core.instancias', verbose_name='superior'),
        ),
        migrations.AddField(
            model_name='funcoes',
            name='organizacao',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='funcoes', to='core.organizacoes', verbose_name='organizacao'),
        ),
        migrations.CreateModel(
            name='DadosMilitantes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=250, verbose_name='nome')),
                ('sindicato', models.CharField(max_length=250, verbose_name='sindicato')),
                ('militante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dados', to='core.militantes', verbose_name='militante')),
            ],
            options={
                'verbose_name': 'funcão',
                'verbose_name_plural': 'funcões',
            },
        ),
        migrations.CreateModel(
            name='AtividadesConfirmacoes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.IntegerField(choices=[(0, 'presente'), (1, 'ausente')], verbose_name='tipo')),
                ('atividade', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='confirmacoes', to='core.atividades', verbose_name='atividade')),
                ('militante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='atividades', to='core.militantes', verbose_name='militante')),
            ],
            options={
                'verbose_name': 'Confirmação de Atividade',
                'verbose_name_plural': 'Confirmações de Atividade',
            },
        ),
        migrations.AddField(
            model_name='atividades',
            name='instancia',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='atividades', to='core.instancias', verbose_name='instancia'),
        ),
        migrations.CreateModel(
            name='Administradores',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('organizacao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='administradores', to='core.organizacoes', verbose_name='instancia')),
                ('usuario', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='administrador', to=settings.AUTH_USER_MODEL, verbose_name='usuario')),
            ],
            options={
                'verbose_name': 'administrador',
                'verbose_name_plural': 'administradores',
            },
        ),
    ]
