# Generated by Django 4.1.7 on 2023-11-14 12:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='funcoes',
            name='assistencia',
        ),
        migrations.AlterField(
            model_name='administradores',
            name='organizacao',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='administradores', to='core.organizacoes', verbose_name='organizacao'),
        ),
    ]
