# Generated by Django 4.1.7 on 2023-11-14 12:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_remove_funcoes_assistencia_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Assistentes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('instancia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assistentes', to='core.instancias', verbose_name='instancia')),
                ('militante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assistencias', to='core.militantes', verbose_name='militante')),
            ],
            options={
                'verbose_name': 'assistentes',
                'verbose_name_plural': 'assistentes',
            },
        ),
    ]
