# Generated by Django 4.1.7 on 2023-11-14 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_dadosmilitantes_atuacao_dadosmilitantes_categoria_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dadosmilitantes',
            name='atuacao',
            field=models.CharField(max_length=250, verbose_name='atuacao'),
        ),
        migrations.AlterField(
            model_name='dadosmilitantes',
            name='categoria',
            field=models.CharField(max_length=250, verbose_name='categoria'),
        ),
    ]
