# Generated by Django 4.1.7 on 2023-11-15 15:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_dadosmilitantes_atuacao_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='assistentes',
            options={'verbose_name': 'assistente', 'verbose_name_plural': 'assistentes'},
        ),
        migrations.AlterModelOptions(
            name='dadosmilitantes',
            options={'verbose_name': 'dados do militante', 'verbose_name_plural': 'dados dos militantes'},
        ),
        migrations.CreateModel(
            name='Contribuicoes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(blank=True, max_length=250, null=True, verbose_name='descrição')),
                ('valor', models.DecimalField(decimal_places=2, default=0.0, max_digits=14, verbose_name='valor')),
                ('data', models.DateField(verbose_name='data')),
                ('instancia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contribuicoes', to='core.instancias', verbose_name='instancia')),
                ('militante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contribuicoes', to='core.militantes', verbose_name='militante')),
            ],
            options={
                'verbose_name': 'contribuicao',
                'verbose_name_plural': 'Contribuições',
            },
        ),
    ]
