# Generated by Django 4.1.7 on 2023-11-15 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_assistentes_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='contribuicoes',
            name='referencia',
            field=models.IntegerField(choices=[(0, 'Outro'), (1, 'Janeiro'), (2, 'Fevereiro'), (3, 'Março'), (4, 'Abril'), (5, 'Maio'), (6, 'Junho'), (7, 'Julho'), (8, 'Agosto'), (9, 'Setembro'), (10, 'Outubro'), (11, 'Novembro'), (12, 'Dezembro'), (13, 'Decimo-Terceiro')], default=0, verbose_name='referencia'),
        ),
    ]
