# Generated by Django 4.1.7 on 2023-11-15 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_contribuicoes_referencia'),
    ]

    operations = [
        migrations.AddField(
            model_name='contribuicoes',
            name='tipo',
            field=models.CharField(default='Mensal', max_length=100, verbose_name='tipo'),
            preserve_default=False,
        ),
    ]
