# Generated by Django 4.1.7 on 2023-11-16 16:32

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_contribuicoes_tipo'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contribuicoes',
            options={'ordering': ['-data', '-referencia'], 'verbose_name': 'contribuicao', 'verbose_name_plural': 'Contribuições'},
        ),
        migrations.RemoveField(
            model_name='atividades',
            name='pauta',
        ),
        migrations.AlterField(
            model_name='atividades',
            name='descricao',
            field=models.TextField(blank=True, null=True, verbose_name='descricao'),
        ),
        migrations.CreateModel(
            name='Convites',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=6, unique=True, verbose_name='codigo')),
                ('criado', models.DateTimeField(default=django.utils.timezone.now, verbose_name='criação')),
                ('instancia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='convites', to='core.instancias', verbose_name='instancia')),
            ],
            options={
                'verbose_name': 'convite',
                'verbose_name_plural': 'convites',
            },
        ),
    ]
