# Generated by Django 4.1.7 on 2023-11-16 21:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_alter_contribuicoes_options_remove_atividades_pauta_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Recrutamentos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=250, verbose_name='nome')),
                ('email', models.EmailField(max_length=250, verbose_name='email')),
                ('telefone', models.CharField(max_length=20, verbose_name='telefone')),
                ('data', models.DateField(verbose_name='data')),
                ('uf_mora', models.CharField(max_length=5, verbose_name='uf mora')),
                ('cidade_mora', models.CharField(max_length=250, verbose_name='cidade mora')),
                ('origemRecrutamento', models.CharField(max_length=250, verbose_name='cidade mora')),
                ('sindicato', models.CharField(max_length=250, verbose_name='sindicato')),
                ('sindicalizado', models.BooleanField(default=False, verbose_name='sindicalizado')),
                ('atuacao', models.CharField(max_length=250, verbose_name='atuacao')),
                ('categoria', models.CharField(max_length=250, verbose_name='categoria')),
                ('tipo_trabalho', models.CharField(max_length=250, verbose_name='tipo de trabalho')),
                ('vinculo_trabalhista', models.CharField(max_length=250, verbose_name='vinculo trabalhista')),
                ('instancia_cadastro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recrutamentos_cadastrados', to='core.instancias', verbose_name='instancia que cadastrou')),
                ('instancia_recrutando', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recrutamentos', to='core.instancias', verbose_name='instancia recrutando')),
                ('militante', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='recrutamento', to='core.militantes', verbose_name='militante')),
            ],
            options={
                'verbose_name': 'recrutamento',
                'verbose_name_plural': 'recrutamentos',
            },
        ),
    ]
