# Generated by Django 4.1.7 on 2023-11-16 21:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_remove_recrutamentos_origemrecrutamento_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='recrutamentos',
            name='status',
            field=models.IntegerField(choices=[(0, 'andamento'), (1, 'recrutado'), (2, 'não recrutado')], default=0, verbose_name='status'),
        ),
    ]
